// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using formpage.Models;

#nullable disable

namespace formpage.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241215163724_AddFiyatColumn")]
    partial class AddFiyatColumn
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("formpage.Models.Otel_Rezervasyonlar", b =>
                {
                    b.Property<string>("RezervasyonId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Cıkıs_tarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Giris_tarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Oda_no")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OtelID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OtelName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rezervasyondurumu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RezervasyonId");

                    b.ToTable("Otel_Rezervasyonlar");
                });

            modelBuilder.Entity("formpage.Models.Oteller", b =>
                {
                    b.Property<int>("OtelID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OtelID"));

                    b.Property<DateTime?>("No_10_cıkıs")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("No_10_giris")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("No_11_cıkıs")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("No_11_giris")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("No_12_cıkıs")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("No_12_giris")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("No_13_cıkıs")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("No_13_giris")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("No_14_cıkıs")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("No_14_giris")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("No_15_cıkıs")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("No_15_giris")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("No_16_cıkıs")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("No_16_giris")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("No_17_cıkıs")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("No_17_giris")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("No_18_cıkıs")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("No_18_giris")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("No_19_cıkıs")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("No_19_giris")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("No_1_cıkıs")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("No_1_giris")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("No_20_cıkıs")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("No_20_giris")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("No_2_cıkıs")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("No_2_giris")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("No_3_cıkıs")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("No_3_giris")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("No_4_cıkıs")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("No_4_giris")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("No_5_cıkıs")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("No_5_giris")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("No_6_cıkıs")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("No_6_giris")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("No_7_cıkıs")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("No_7_giris")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("No_8_cıkıs")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("No_8_giris")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("No_9_cıkıs")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("No_9_giris")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Oda_no1")
                        .HasColumnType("bit");

                    b.Property<bool>("Oda_no10")
                        .HasColumnType("bit");

                    b.Property<string>("Oda_no10_user")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Oda_no11")
                        .HasColumnType("bit");

                    b.Property<string>("Oda_no11_user")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Oda_no12")
                        .HasColumnType("bit");

                    b.Property<string>("Oda_no12_user")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Oda_no13")
                        .HasColumnType("bit");

                    b.Property<string>("Oda_no13_user")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Oda_no14")
                        .HasColumnType("bit");

                    b.Property<string>("Oda_no14_user")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Oda_no15")
                        .HasColumnType("bit");

                    b.Property<string>("Oda_no15_user")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Oda_no16")
                        .HasColumnType("bit");

                    b.Property<string>("Oda_no16_user")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Oda_no17")
                        .HasColumnType("bit");

                    b.Property<string>("Oda_no17_user")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Oda_no18")
                        .HasColumnType("bit");

                    b.Property<string>("Oda_no18_user")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Oda_no19")
                        .HasColumnType("bit");

                    b.Property<string>("Oda_no19_user")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Oda_no1_user")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Oda_no2")
                        .HasColumnType("bit");

                    b.Property<bool>("Oda_no20")
                        .HasColumnType("bit");

                    b.Property<string>("Oda_no20_user")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Oda_no2_user")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Oda_no3")
                        .HasColumnType("bit");

                    b.Property<string>("Oda_no3_user")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Oda_no4")
                        .HasColumnType("bit");

                    b.Property<string>("Oda_no4_user")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Oda_no5")
                        .HasColumnType("bit");

                    b.Property<string>("Oda_no5_user")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Oda_no6")
                        .HasColumnType("bit");

                    b.Property<string>("Oda_no6_user")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Oda_no7")
                        .HasColumnType("bit");

                    b.Property<string>("Oda_no7_user")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Oda_no8")
                        .HasColumnType("bit");

                    b.Property<string>("Oda_no8_user")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Oda_no9")
                        .HasColumnType("bit");

                    b.Property<string>("Oda_no9_user")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OtelName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fiyat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sehir")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OtelID");

                    b.ToTable("Oteller");
                });

            modelBuilder.Entity("formpage.Models.Otobus", b =>
                {
                    b.Property<string>("Otobus_Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Plaka")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sofor_adı_soyadı")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("firma_adı")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Otobus_Id");

                    b.ToTable("Otobus");
                });

            modelBuilder.Entity("formpage.Models.Otobus_rezervasyon", b =>
                {
                    b.Property<string>("RezervasyonId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Rezervasyondurumu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SeferId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("User_ID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("koltukno")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RezervasyonId");

                    b.ToTable("Otobus_rezervasyon");
                });

            modelBuilder.Entity("formpage.Models.Seferler", b =>
                {
                    b.Property<string>("SeferId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Baslangıc_sehir")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Varıs_sehri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("baslangıc_tarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("fiyat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("koltuk_1")
                        .HasColumnType("bit");

                    b.Property<bool>("koltuk_10")
                        .HasColumnType("bit");

                    b.Property<string>("koltuk_10user")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("koltuk_11")
                        .HasColumnType("bit");

                    b.Property<string>("koltuk_11user")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("koltuk_12")
                        .HasColumnType("bit");

                    b.Property<string>("koltuk_12user")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("koltuk_13")
                        .HasColumnType("bit");

                    b.Property<string>("koltuk_13user")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("koltuk_14")
                        .HasColumnType("bit");

                    b.Property<string>("koltuk_14user")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("koltuk_15")
                        .HasColumnType("bit");

                    b.Property<string>("koltuk_15user")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("koltuk_16")
                        .HasColumnType("bit");

                    b.Property<string>("koltuk_16user")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("koltuk_17")
                        .HasColumnType("bit");

                    b.Property<string>("koltuk_17user")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("koltuk_18")
                        .HasColumnType("bit");

                    b.Property<string>("koltuk_18user")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("koltuk_19")
                        .HasColumnType("bit");

                    b.Property<string>("koltuk_19user")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("koltuk_1user")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("koltuk_2")
                        .HasColumnType("bit");

                    b.Property<bool>("koltuk_20")
                        .HasColumnType("bit");

                    b.Property<string>("koltuk_20user")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("koltuk_21")
                        .HasColumnType("bit");

                    b.Property<string>("koltuk_21user")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("koltuk_22")
                        .HasColumnType("bit");

                    b.Property<string>("koltuk_22user")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("koltuk_23")
                        .HasColumnType("bit");

                    b.Property<string>("koltuk_23user")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("koltuk_24")
                        .HasColumnType("bit");

                    b.Property<string>("koltuk_24user")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("koltuk_25")
                        .HasColumnType("bit");

                    b.Property<string>("koltuk_25user")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("koltuk_26")
                        .HasColumnType("bit");

                    b.Property<string>("koltuk_26user")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("koltuk_27")
                        .HasColumnType("bit");

                    b.Property<string>("koltuk_27user")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("koltuk_28")
                        .HasColumnType("bit");

                    b.Property<string>("koltuk_28user")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("koltuk_29")
                        .HasColumnType("bit");

                    b.Property<string>("koltuk_29user")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("koltuk_2user")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("koltuk_3")
                        .HasColumnType("bit");

                    b.Property<bool>("koltuk_30")
                        .HasColumnType("bit");

                    b.Property<string>("koltuk_30user")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("koltuk_31")
                        .HasColumnType("bit");

                    b.Property<string>("koltuk_31user")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("koltuk_32")
                        .HasColumnType("bit");

                    b.Property<string>("koltuk_32user")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("koltuk_33")
                        .HasColumnType("bit");

                    b.Property<string>("koltuk_33user")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("koltuk_34")
                        .HasColumnType("bit");

                    b.Property<string>("koltuk_34user")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("koltuk_35")
                        .HasColumnType("bit");

                    b.Property<string>("koltuk_35user")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("koltuk_36")
                        .HasColumnType("bit");

                    b.Property<string>("koltuk_36user")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("koltuk_37")
                        .HasColumnType("bit");

                    b.Property<string>("koltuk_37user")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("koltuk_38")
                        .HasColumnType("bit");

                    b.Property<string>("koltuk_38user")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("koltuk_39")
                        .HasColumnType("bit");

                    b.Property<string>("koltuk_39user")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("koltuk_3user")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("koltuk_4")
                        .HasColumnType("bit");

                    b.Property<bool>("koltuk_40")
                        .HasColumnType("bit");

                    b.Property<string>("koltuk_40user")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("koltuk_4user")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("koltuk_5")
                        .HasColumnType("bit");

                    b.Property<string>("koltuk_5user")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("koltuk_6")
                        .HasColumnType("bit");

                    b.Property<string>("koltuk_6user")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("koltuk_7")
                        .HasColumnType("bit");

                    b.Property<string>("koltuk_7user")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("koltuk_8")
                        .HasColumnType("bit");

                    b.Property<string>("koltuk_8user")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("koltuk_9")
                        .HasColumnType("bit");

                    b.Property<string>("koltuk_9user")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("otobus_Id")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sefer_durumu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("varıs_tarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("SeferId");

                    b.ToTable("Seferler");
                });

            modelBuilder.Entity("formpage.Models.User", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Account_Status")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone_Num")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Reg_Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("S_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("verify_email")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
